### ISSUE TITLE
Feature: Gateway configuration API

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi-network-serverless#1]
Specify and implement API for gateway configuration, for example how often data should be posted by gateway

**Comment by Muhwu** [comment]
This is currently behind deployment - i.e. the header is being returned already. The two ways to change it are:

1. Change `GATEWAY_SEND_RATE` environment vraible directly on the lambda (this will be overwritten on deployment)
2. Change `gatewaySendRate` on serverless.yml and deploy

If this needs to be changed more often, the options are to either make it an endpoint or wrap an AWS env update CLI call in a script. If it needs automatic adjusting, more complex options can be explored.

The rate will be returned in the header `x-ruuvi-gateway-rate` in the responses to `{API_URL}/record` as _seconds between updates_
