### ISSUE TITLE
Default background for tags

### ISSUE THREAD

**Issue by io53** [ruuvi/ruuvi-network-serverless#103]
Unless you have uploaded a background for a tag, there is no info in network about what default background to show. This resulting in different background showing in the apps.

Could the default background number for a tag somehow be in the network response?
Using the "picture" property or a new one?
@rinat-enikeev @andreevdenis

**Comment by andreevdenis** [comment]
Network doesn't have field for default background number. It can be added easily by Sami, but I think we should discuss it first

**Comment by Muhwu** [comment]
Are the defaults user or sensor specific? `/settings` endpoint allows storing key-value pairs so if they're user specific, that might be a good place for them. If they can vary per sensor, then perhaps extending the sensor `/update` method would be in order.

**Comment by Muhwu** [comment]
We'll add `defaultBackground` parameter to `/update` (sensor) end-point that takes in a string. We can store filename or unique identifier of the default background there.

**Comment by Muhwu** [comment]
Change to plan - `update` end-point now accepts a string identifier that CANNOT be a URL. This means that the user will not be able to point to a random URL, but will be able to provide an identifier. It is up to the app to use a default picture appointed by the identifier or the filename. The setting / parameter is called `picture`.
