### ISSUE TITLE
Make login code email's link to open the web app on a desktop browser

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi-network-serverless#115]
Let's discuss if it would be possible to create a link that would log in automatically user on station.ruuvi.com but that would not interfere with the mobile apps (if installed). Only one link for all (Android, iOS, Web) is preferred solution. Plan B is to have a separate link for the web.

Chat log:

![image](https://user-images.githubusercontent.com/1311912/128376935-f414c2ff-db35-4eb3-a90d-f17269555f5b.png)

**Comment by andreevdenis** [comment]
@io53 if link for login will be similar to https://station.ruuvi.com/verify?token={token} I can easily reconfigure app and user will have option to open link with Ruuvi Station application or in browser

**Comment by io53** [comment]
I'll have to play around a little bit to see what URL would work for the webui. Currently it's using hash routing, so the url might have to be https://station.ruuvi.com/?token={token}. Would that work for the apps?

**Comment by andreevdenis** [comment]
Sure, let's try it.

**Comment by io53** [comment]
Don't do anything to this task yet. I was playing around a bit and I think I can get it to work with the current URL after all 👍. I'll keep you posted

**Comment by andreevdenis** [comment]
Sorry for delay. It's was very easy to migrate to new URL. Not sure if it will be the same for @rinat-enikeev

**Comment by rinat-enikeev** [comment]
Atm iOS works with the link https://network.ruuvi.com/verify?token=XXXX because we've added `apple-app-site-association` file here https://network.ruuvi.com/apple-app-site-association. 

In case we want to support different subdomain the first step is to add `apple-app-site-association` to desired subdomain. 

Without adding file the link won't work on iOS.

**Comment by io53** [comment]
Is adding the file https://network.ruuvi.com/apple-app-site-association to station.ruuvi.com the only action needed for iOS to work with https://station.ruuvi.com/verify?token=XXXX ? I can do that right away if so

**Comment by rinat-enikeev** [comment]
seems it can work, let me try to debug. Please add `AASA` file to subdomain and ping me - I'll construct the link myself and test.

**Comment by andreevdenis** [comment]
@Muhwu will make changes to Cloud side within an hour so we'll be able to test it soon

**Comment by ojousima** [comment]
This is now implemented and can be closed?
