### ISSUE TITLE
Sensors were synced to me in different order

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi-network-serverless#126]
Description:

User aamunkajom@gmail.com has multiple network sensors that were listed in order:

Rinat UFA
ESTRELLA
OH JOY this name is gonna be veryveryveryveryveryvery...
Home Outside 😎
Ruuvi ABCD

Then he signed into network multiple times on various devices
Shared couple of his network sensors
Renamed Ruuvi ABCD to Wowza

Again reinstalled app and signed into client
Now network sensors order has changed to

Wowza
OH JOY this name is gonna be veryveryveryveryveryvery...
Home Outside 😎
ESTRELLA
Rinat UFA

---

Retried the test with fresh sensor and default name Ruuvi C909, claimed it to network. This was the last sensor at the right of the list. Synced to network, then uninstalled app and reinstalled app, signed into network again.

Now this sensor is second sensor card in the list from the left.
This could be some sort of bug when adding and syncing sensors with default name.

**Comment by laurijamsa** [comment]
Happened to me too. This is related to the missing feature: make it possible to reorganise sensors. We'll need that feature later, but let's fix other issues first. I'm moving this one to the backlog for now.

**Comment by ojousima** [comment]
Should the sensors have a "sort priority" list? That would be a hidden element that has the index of sensor ordering, perhaps by default app should sort the sensors alphabetically and add corresponding sort priority to them?

It does raise some questions, for example how tags are sorted in case a sensor is renamed. Should it keep it's position, move to new alphabetical position, other, what?

I propose we drop this issue for now, users can order their tags with prefix number if they want to.

**Comment by laurijamsa** [comment]
I agree with closing this one for now as alphabetical sorting has been already implemented on the client side and we have received no feedback that it would be not a good solution.
