### ISSUE TITLE
When unclaiming a sensor, all alert settings should be cleared

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi-network-serverless#132]
If not doing so, really weird things can happen. I had hard time figuring out what the heck was happening, but I think the reason was that I unclaimed a sensor that had alerts configured and later when I claimed it again, those old settings were functional and Android app didn't sync those from the cloud during claiming. I think it's not necessary to remember those after unclaim, so let's just flush them and keep things more simple.

EDIT: I reproduced this issue.

**Comment by Muhwu** [comment]
Right, yeah, those aren't properly cleared at the moment - will address.
