### ISSUE TITLE
Cloud is rejecting some of the data packets

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi-network-serverless#136]
My Gateway is sending every 1min (see the log and timestamps) but when I check webUI, not every transmission is stored to the cloud. Some of these data transmissions are discarded and there are 2 min gaps between data points. Can this happen if there is only 59 seconds between 2 timestamps?

[log.txt](https://github.com/ruuvi/ruuvi-network-serverless/files/7070476/log.txt)

**Comment by laurijamsa** [comment]
This is fixed in the latest cloud deployment. Closing.

**Comment by laurijamsa** [comment]
Reopening. This is happening again. When I browse stored measurements, I see 2 and 3 minute gaps on the data. This happens with 3 different Gateways that are in different locations. See video:

https://user-images.githubusercontent.com/1311912/139578446-21293f77-9835-4ddb-ba26-21e4af0585fc.mov

**Comment by ojousima** [comment]
This doesn't seem to be valid issue anymore, at least I don't see gaps in my data. @laurijamsa please check and close if you can't replicate this anymore
