### ISSUE TITLE
No ruuviTags show network status, i.e. owner ; shared - defect 

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi-network-serverless#138]
On both ruuviStation (android) and RuuviStation.IOS logged in user with RuuviTags owned ; currently only show
remove

PS GET 'https://network.ruuvi.com/get?sensor=D0:FD:6D:65:06:DC... should include version

Currently includes timestamps (outside of JSON) example 
```
1630340495
XXXX (((low order 4 digits of MAC address)))
{
 "result...
   "data...
     "sensor...
        "measurements":[
               {
...
...
        "total": 15,
        "public": 0,
        "table": "prod-SensorDataReduced",
        "resolvedMode": "sparse"
    }
}Now:1630340496

```

**Comment by laurijamsa** [comment]
Could you please be more specific? What do you mean by "only show remove"? In the latest app updates, ownership and sharing information are shown next to the name on the sensor settings page.

**Comment by DG12** [comment]
Ah Yeah! :-)
