### ISSUE TITLE
~~Share automatically a demo sensor to new accounts~~ Setup public sensors that can be used as a demo

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi-network-serverless#144]
This way mobile apps and web interface can be tested by potential customers without buying hardware first.

The demo sensor and Ruuvi Gateway nearby it should be on 24/7/365. We'll give MAC address of the final demo sensor after this feature has been implemented to the cloud.

**Comment by ojousima** [comment]
#198 depends on this

**Comment by laurijamsa** [comment]
> #198 depends on this

Hmm, why?

**Comment by ojousima** [comment]
>> https://github.com/ruuvi/ruuvi-network-serverless/issues/198 depends on this

> Hmm, why?

To have test data available

**Comment by andreevdenis** [comment]
You sure we want this to work automatically? Some sensor appeared from nowhere in app may confuse someone. Maybe we should ask user if he want a demo and if he agree we'll send request to some new endpoint.

**Comment by ojousima** [comment]
The demo functionality could be done with public sensors. Ruuvi needs to set up a few sensors, set them as public, and then user can subscribe to those through some "see demo" button
