### ISSUE TITLE
Renamed shared sensor is not returned and removed from owners shared sensors list when deleted

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi-network-serverless#147]
Description:

Owner shared a sensor named "The Devil" to a user and user received it to his app when cloud was synced.
User then renamed sensor to "A Devil" and then deleted shared sensor.

Owners shared sensors list doesn't update and remove the returned sensor from the list.

Android card for reference:
https://github.com/ruuvi/com.ruuvi.station/issues/475

https://user-images.githubusercontent.com/50437378/132274683-e195a86b-8b62-4cc5-a842-01a2f8470927.mov

**Comment by laurijamsa** [comment]
I cannot reproduce this.

**Comment by andreevdenis** [comment]
I can reproduce. No need to rename - just remove shared sensor. It looks like it wasn't deleted at server side, it will return with next sync.

**Comment by andreevdenis** [comment]
Looks like problem is on my side. This issue can be closed
