### ISSUE TITLE
Alert limit test  must include sensor correction

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi-network-serverless#157]
09/16/21 at 15:18 EDT
Alert:

Dehumidifier 09:81 has reached 50.83% (humidity) that is over the threshold of 57%.
Seems that humidity has reached 58%

**Comment by ojousima** [comment]
Does your sensor have some calibration level on it?

**Comment by DG12** [comment]
Yes EXACTLY 6.17% !! Bingo

**Comment by ojousima** [comment]
Have I understood correctly?
1) Your sensor raw data was 50.83 %
2) The sensor has calibration +6.17 %
3) You have configured alert on >57 %.
4) You received alert "Sensor 09:81" has reached humidity 50.83 % which is higher than 57 %

**Comment by DG12** [comment]
Correct.

**Comment by ojousima** [comment]
This is fixed as of today
