### ISSUE TITLE
Alerts testing should be suspended for a short time after being changed

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi-network-serverless#158]
adjusting the alert limits is awkward which can result in user setting limits, observing them and changing them.
This can cause undesirable alert messages.
Perhaps not testing limits for a minute or so after being changes would prevent this.

**Comment by ojousima** [comment]
I think this is more about Station app and webpage than backend?

**Comment by DG12** [comment]
Seems that since the "backend" generates alerts (?) this t
yep of issue is better handled in the backend rather than in station.android AND station.IOS and station.web

**Comment by ojousima** [comment]
The alerts have hysteresis now, which limits the number of alerts send. Closing
