### ISSUE TITLE
email: Ruuvi sensor <<unnamed>> has been removed

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi-network-serverless#164]
After removing dehumidifier   0981 sensor which was shared with msimsgerman@gmail
owner receives email:

```
The sensor <> has been removed from your Ruuvi account
This sensor was removed or the sharing was cancelled by the owner (dg@cccu.us).
If you don’t recognise dg@cccu.us, you can ignore this email.
```

"Sharee" received email with correct name

**Comment by DG12** [comment]
subject Ruuvi sensor <<unnamed>> has been removed
body: The sensor <> has been removed from your Ruuvi account

I just removed 2 sensors via stationIOS which didn't have recent data.

**Comment by ojousima** [comment]
I tried to replicate this with Ruuvi Station Android.

Steps:
1) Claim ownership os a sensor
2) Share sensor to another account
3) Remove ownership of a sensor

Result: Another account gets 2 emails, one for share and one for unshare. Owner account does not get emails. Does this work differently for you with current versions @DG12?
