### ISSUE TITLE
Per-sensor configurable UI settings

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi-network-serverless#203]
- Visible on off
- "Main" unit of measurement

**Comment by laurijamsa** [comment]
What about if there would be just one customisable key-value pair table for the each sensor? This way the backend wouldn't need to be always modified if a new unit will be added in the client side. This would be possible to do this way if we decide that https://github.com/ruuvi/ruuvi-network-serverless/issues/202 is not a needed feature.

Same idea as here but the values would be stored under sensors' settings in the backend and not under user account: https://github.com/ruuvi/com.ruuvi.station.webui/issues/141
