### ISSUE TITLE
Weird data pruning behaviour (?)

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi-network-serverless#21]
These shared sensors should have continuous data available but syncing gives only 1h and 13h frequent data and the rest is really random:

![image](https://user-images.githubusercontent.com/1311912/99192451-9ccbe180-277b-11eb-82e4-338ca8f57814.png)

![image](https://user-images.githubusercontent.com/1311912/99192458-a5bcb300-277b-11eb-9f45-bda09937a443.png)

**Comment by Muhwu** [comment]
So I'm not exactly sure what caused there to be so much recent data, but the data fetching things were definitely broken.

I added a `table` variable to return values for `getSensorData` so you will see whether it comes from the reduced data or the "full" data and can figure out whether something is awry.

Furthermore, the limit is currently *3 hours* for the high resolution data and the interval between _accepted data points_ is 15 minutes (meaning if the gateway sends data more often, it will not be stored to the reduced table).
