### ISSUE TITLE
[Edit] Compress transmitted data 

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi-network-serverless#218]
```
 .htaccess

   # BEGIN GZIP
   <ifmodule mod_deflate.c>
   AddOutputFilterByType DEFLATE text/text text/html text/plain text/xml text/css application/x-javascript application/javascript
   </ifmodule>
   # END GZIP
```

I think I have seen discussion that says that  deflate does not work with SSL.

HOWEVER, zipping data "manually" and then sending it out with SSL should greatly reduce transmission time.

(Is this the correct repository for this )

**Comment by ojousima** [comment]
This is a good point. Currently data is not compressed, but especially the history data could benefit from compression when fetching long time intervals. I'm not sure on how much integration work there would be, but in best case it would be just a few configuration flags. @Muhwu Your thoughts?

**Comment by ojousima** [comment]
This would require encoding / decoding the payloads programmatically. The change would break the current apps, so if this ever gets implemented we need a v2 API

**Comment by DG12** [comment]
Server should be able to determine if client version can accept compressed format.  This would mitigate breaking apps that don't support compression.

Testing suggests compressed would take only 20% of current transmission. This becomes more important as requested time period extends.

**Comment by ojousima** [comment]
The limitation comes from AWS side, there's no support for automatic compression in functions we're using. This means that supporting the compression requires custom implementation. It might be possible to write the standard compression logic in DIY manner to lambdas we're using, but overall it would be error-prone and require careful maintenance
