### ISSUE TITLE
Sharing a claimed sensor that is not scanned by a gateway should be restricted

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi-network-serverless#22]
Otherwise the sharee would think that something is broken and that would be a bad user experience.

**Comment by Muhwu** [comment]
Just to clarify - Do you mean that if no data exists for a sensor, you shouldn't be able to share it?

**Comment by laurijamsa** [comment]
Yes, exactly, as currently Gateway is the only device that is able to store data to the database.

**Comment by Muhwu** [comment]
I guess another clarification here - should we still be able to claim such sensor ?

**Comment by ojousima** [comment]
As the sensor claims are used to transfer settings between phones, I'd say yes.

**Comment by Muhwu** [comment]
This is done.
