### ISSUE TITLE
Add endpoint to fetch latest datapoint of each sensor of a subscription

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi-network-serverless#221]

**Comment by andreevdenis** [comment]
@ojousima @Muhwu @priyonto 
What is the difference between **user** and **sensors** endpoints? These two looks almost the same to me. Will we add another very similar endpoint for current task or we can include latest datapoint to one of these existing enpoints?

Also I want to remind to include calibration data to response.

**Comment by ojousima** [comment]
It might make sense to expand the `sensors` endpoint with latest datapoint. 

Endpoint `user` should return all user data, including subscription type etc in the future
