### ISSUE TITLE
threshold for humidity increased by owner, sharee correctly still receives alerts

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi-network-serverless#235]
I have changed the upper threshold for BB12 from 55 to 58% and the emails keep coming.

<img width="640" alt="HumidityChangeUpperThersholdNotUsed" src="https://user-images.githubusercontent.com/2365961/175841734-c56213dc-b4b6-4cec-99a5-ddf502972519.png">

Please make it stop :-)

https://ejunkieblog.files.wordpress.com/2020/11/tumblr_p4z9m49rmr1w3qc55o3_500.gif

Please resubmit if this it no the correct repository.

**Comment by ojousima** [comment]
This seems to be related to sharing sensors, I contacted you directly about the steps to check

**Comment by DG12** [comment]
Working as it should!  Closed user misunderstanding.
Owner changes threshold and no longer receives alerts.
Sharee still has threshold set below current value and so correctly receives alerts.
