### ISSUE TITLE
alerts for a single over limit occurs more than1 per minute - defect - !important

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi-network-serverless#238]
Suddenly On 09/20/22 Alerts for 20BC being over humidity limit occur more than once per minute.
.... 7.16:02, 7:16:20, 7:17:20, 7:18:18, 7:19:04, 7:20:05 ..
Disabling alert from iPhone stopped alerts.
Using iPhone to Enable alert 13 hours later and alerts continue.
:![image](https://user-images.githubusercontent.com/2365961/191504099-859b5f9b-7039-4020-9726-0ae3aa0c2640.png)

Hope this is the correct repository for this issue.

**Comment by ojousima** [comment]
Sorry about long reply time. 

Since this is about push notifications, this is coming on iOS itself. I'll link this to iOS repository.

**Comment by ojousima** [comment]
iOS issue is here: https://github.com/ruuvi/com.ruuvi.station.ios/issues/1122
