### ISSUE TITLE
Error codes for localized domains

### ISSUE THREAD

**Issue by Muhwu** [ruuvi/ruuvi-network-serverless#36]
All API errors should return an error code giving more information on the error to allow localization on mobile apps.

An example could look something like this:
```
{
  "status": "error",
  "error": "Sensor has already been claimed.",
  "errorCode": "ER_SENSOR_ALREADY_CLAIMED"
}
```
or we could go with an integer based approach:
```
{
  "status": "error",
  "error": "Sensor has already been claimed.",
  "errorCode": 88001
}
```
and if we need a  `code` + `subCode` - we could also do:
```
{
  "status": "error",
  "error": "Internal server error",
  "errorCode": 1,
  "errorSubCode": 13391
}
```

Thoughts? The HTTP error codes would still remain as is, so in my opinion #1 or #2 would probably be enough to cover all bases.

**Comment by andreevdenis** [comment]
I vote for 1st option

**Comment by Muhwu** [comment]
Sold! We'll proceed with that assumption. It's not tough to change on the API side later, but in all fairness it probably doesn't matter all that much and human readable has the advantage of being... human readable.
