### ISSUE TITLE
Support sharing sensor to new user

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/ruuvi-network-serverless#49]
Lauri: When sharing a sensor to a friend, I get message "user not found". We want to support sharing to new users too 🤔

**Comment by Muhwu** [comment]
Does this mean that sharing to a non-existing user creates some kind of invite for them to sign up?

**Comment by ojousima** [comment]
@laurijamsa @andreevdenis ^

**Comment by andreevdenis** [comment]
If I was doing it on server side I'd use existing code:
1) Create new user
2) share sensor as always
3) send email to user with invitation (new)

Do you see it differently @laurijamsa ?

**Comment by ojousima** [comment]
@laurijamsa ping

**Comment by laurijamsa** [comment]
Yes, an invitation email should be sent if a sensor is shared to someone without a Ruuvi Network account.

We will polish the actual email later and in the beginning it could just give app download links for Android and iOS and state that to see the shared sensors, please install the app and log in using this same email address. Email title could be: "Ruuvi user lauri@ruuvi.com has shared a sensor with you"
