### ISSUE TITLE
Move auth to Custom Authorizer

### ISSUE THREAD

**Issue by Muhwu** [ruuvi/ruuvi-network-serverless#63]

**Comment by ojousima** [comment]
This provides DDOS protection.

UserAPI: Token
GatewayAPI: Signature

https://www.serverless.com/framework/docs/providers/aws/events/apigateway#http-endpoints-with-custom-authorizers

Requires IAM access policy adjustments

**Comment by ojousima** [comment]
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html

**Comment by ojousima** [comment]
See also #66
