### ISSUE TITLE
metrics endpoint should include MM/DD/YY hh:mm:ss - enhancement

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi-network-serverless#76]
It would be very helpful to understand metrics.

**Comment by Muhwu** [comment]
The timestamps are standard Unix timestamps and can easily be converted on the receiving end. I agree that for anyone poking the API by hand, it would be more convenient to see the dates in text format, converting them programmatically on the API side muddies the waters for the API and is in vast majority of cases unnecessary.

Doing the conversion in, for example, JavaScript can be done with a few neat lines:
```
const unixTimestamp = sensorData.timestamp
const dateObject = new Date(unixTimestamp * 1000)
const humanDateFormat = dateObject.toLocaleString()
```
