### ISSUE TITLE
Schedule/disable/enable network alert emails

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi-network-serverless#84]
Hi, is it technically possible to schedule, or disable/enable network alert emails?
Lets say that we would give user option to edit this from web or apps?

**Comment by markoaamunkajo** [comment]
This question is for @Muhwu

**Comment by laurijamsa** [comment]
One idea would be to include a unique link on the alarm notification email like "Disable this alarm" or/and "Snooze this alarm for 24 hours". Technically straightforward to create URLs like that? (would need a success page to be shown after user opens the link)

**Comment by Muhwu** [comment]
There's some preliminary work set up for this. Lauri's idea is also a good option and maybe there could be many ways of doing it.

**Comment by ojousima** [comment]
Users can disable alerts manually if needed, closing for now. Let's review if we get feedback on it.
