### ISSUE TITLE
Cloud management functions: suspend/reactivate & delete 

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi-network-serverless#85]
There needs to be a means to delete a tag that is lost, broken etc.

There needs to be a means to suspend a tag (in particular related to subscription plan).
Scenario is I have 10 active(max free subscription). I deploy 3 to the field i.e. out of range. 
I buy 3 more. I retrieve 1 from the field and suspend  (at least 1) etc, etc

See also station & station IOS

**Comment by DG12** [comment]
Please consider this carefully.
unclaim does not accomplish this.

**Comment by laurijamsa** [comment]
This would add unnecessary complexity at this stage and we're aiming to come up with a more simple solution for this "issue". Closing.
