### ISSUE TITLE
Show masked owner email in sensor already claimed message

### ISSUE THREAD

**Issue by andreevdenis** [ruuvi/ruuvi-network-serverless#86]
This needs to be discussed before implementing.

It will be nice to provide masked owner email when we get error: sensor already claimed. It might help user in case if he already claimed sensor from another account or if some of his family members did it.

How to keep ability to localize message? Maybe sensor response should use code for "sensor already claimed" and error should only have masked owner email.

Email hidden format: otso.jousimaa@gmail.com -> ot ... aa@gm...com?

**Comment by Muhwu** [comment]
MVP: `First + ... + last@first + ... + domain`

**Comment by Muhwu** [comment]
Not quite the algorithm as above (There's a minor tweak for shorter ones and it also takes `.` into account for a bit more visibility). There is a test in `maskEmail.test.js` to illustrate the format.
