### ISSUE TITLE
get?sensor=MAC needs to include current timestamp -  improvement

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi-network-serverless#88]
Response from
get?sensor=D0:FD:6D:65:06:DC' 
should include current timestamp after "success"

<pre>{
    "result": "success",
    "data": {
        "sensor": "D0:FD:6D:65:06:DC",
        "name": "Ruuvi_06DC",
        "offsetTemperature": 0,
        "offsetHumidity": 0,
        "offsetPressure": 0,
        "measurements": [
            {
                "coordinates": "N/A",
                "data": "0201041BFF99040511615022C789009CFFD403E08836153EB3D0FD6D6506DC",
                "gwmac": "24:0A:C4:E2:D8:28",
                "timestamp": 1621869796,
                "rssi": -83
            },
            {
                "coordinates": "N/A",
                "data": "0201041BFF990405100F5018C79200CC007803C48756103E7AD0FD6D6506DC",
                "gwmac": "24:0A:C4:E2:D8:28",
                "timestamp": 1621869722,
                "rssi": -56
            },</pre>
following entries coordinates N/A and gwmac deleted and edited  for brevity 
 <pre>data: ...0FFC4C49C79C0030001003FC87560F3E41..., timestamp: 1621869649, rssi: -72
 data: ...0FFC4C49C79B002C001803F387560F3E06..., timestamp: 1621869574, rssi: -82
 data: ...0FFB4C4DC79F0030001403FC86D60F3DCE..., timestamp: 1621869502, rssi: -70
 data: ...0FFC4C45C7990028001803F887B60F3D95..., timestamp: 1621869428, rssi: -70
 data: ...0FFC4C49C7960030001403FC88360F3D5C..., timestamp: 1621869355, rssi: -70
 data: ...0FFD4C45C793002C001803EB87560F3D22..., timestamp: 1621869281, rssi: -70
 data: ...0FFD4C4BC78F002C001403F887560F3CE4..., timestamp: 1621869201, rssi: -70
 data: ...0FFD4C45C792002C001803F887B60F3CB0..., timestamp: 1621869134, rssi: -70
 data: ...0FFE4C41C7920038001403F888360F3C77..., timestamp: 1621869061, rssi: -70
 data: ...0FFE4C3CC7910030001403F387B60F3C3E..., timestamp: 1621868987, rssi: -69
 data: ...0FFE4C41C7980030001003F888360F3C04..., timestamp: 1621868914, rssi: -70
 data: ...0FFF4C3FC7950030001403F888360F3BCB..., timestamp: 1621868840, rssi: -70
 data: ...0FFE4C3CC79400280014040087560F3B91..., timestamp: 1621868765, rssi: -71

        ],
        "total": 15,
        "public": 0,
        "table": "prod-SensorDataReduced",
        "resolvedMode": "sparse"
    }
}</pre>

**Comment by Muhwu** [comment]
Current time is the global Unix timestamp (i.e. world clock) so one can get it on local, for example, with JavaScript with
```
Math.floor(Date.now() / 1000)
```

Furthermore, the HTTP response headers will have the timestamp in human readable form (example from Postman)
![image](https://user-images.githubusercontent.com/9969729/123105101-2f361100-d440-11eb-8a17-0115f302e7b0.png)

**Comment by DG12** [comment]
The time the ruuvi-network-serverless thinks it is (Not the time on the local system) should be included in the response.

**Comment by ojousima** [comment]
Networked computers can be assumed to have network time from NTP server.

**Comment by DG12** [comment]
If the response from the get? is (perhaps periodically) saved to a file It would be helpful for the response to include the timestamp. Is this an unusual use case?
